#!/opt/bin/php
<?php
/**
 * This file will be a "Front Controller" for requests.
 * @see https://aws.amazon.com/premiumsupport/knowledge-center/malformed-502-api-gateway/
 * @see https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html
 */
